timezone = "local"
auto_sync = true
update_check = true
sync_address = "https://api.atuin.sh"
sync_frequency = "60m"
filter_mode = "global"
enter_accept = true
history_filter = [
]

[sync]
records = true
