source ~/.config/theme/theme

SPACESHIP_TIME_SHOW=false
SPACESHIP_USER_SHOW=false
SPACESHIP_DIR_TRUNC_REPO=true

SPACESHIP_CHAR_COLOR_SUCCESS=$GREEN
SPACESHIP_CHAR_COLOR_FAILURE=$RED
SPACESHIP_CHAR_COLOR_SECONDARY=$YELLOW

SPACESHIP_DIR_COLOR=$GREEN
SPACESHIP_DIR_LOCK_COLOR=$RED

SPACESHIP_GIT_BRANCH_COLOR=$YELLOW
SPACESHIP_GIT_STATUS_COLOR=$YELLOW

SPACESHIP_PACKAGE_COLOR=$RED

SPACESHIP_ANSIBLE_COLOR=$WHITE

SPACESHIP_DOCKER_COLOR=$RED
SPACESHIP_DOCKER_COMPOSE_COLOR_UP=$GREEN
SPACESHIP_DOCKER_COMPOSE_COLOR_DOWN=$RED
SPACESHIP_DOCKER_COMPOSE_COLOR_PAUSED=$YELLOW

SPACESHIP_RUST_COLOR=$RED
SPACESHIP_NODE_COLOR=$RED

SPACESHIP_EXEC_TIME_COLOR=$YELLOW
